databases:
  - name: vibe-chat-db
    plan: free
    postgresVersion: 15

services:
  - type: web
    name: vibe-chat-backend
    env: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: base64:pKDb3xXy3F4Prh+cTDaiSn8p3dEjosN5SpJEbUj98j0=base64:E/GohRh4YbOAOCZyFNMllWlv2cFbNqo6fiSJ94FPvVw=
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: vibe-chat-db
          property: host
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        fromDatabase:
          name: vibe-chat-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: vibe-chat-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: vibe-chat-db
          property: password
      - key: DB_SSLMODE
        value: require
