services:
  - type: web
    name: vibechat.service
    env: php
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader
    envVars:
      - key: DOCUMENT_ROOT
        value: public
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: base64:pKDb3xXy3F4Prh+cTDaiSn8p3dEjosN5SpJEbUj98j0=base64:E/GohRh4YbOAOCZyFNMllWlv2cFbNqo6fiSJ94FPvVw=
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ep-rough-firefly-attnaka8-pooler.c-9.us-east-1.aws.neon.tech
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: vibe_chat_db
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        value: endpoint=ep-rough-firefly-attnaka8;npg_ct85wfbFZuEP
      - key: DB_SSLMODE
        value: require
