services:
  - type: web
    name: vibechat.service
    env: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: base64:pKDb3xXy3F4Prh+cTDaiSn8p3dEjosN5SpJEbUj98j0=
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ep-rough-firefly-attnaka8-pooler.c-9.us-east-1.aws.neon.tech
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: vibe_chat_db
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_ct85wfbFZuEP
      - key: DB_SSLMODE
        value: require
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_STORE
        value: file
      - key: FILESYSTEM_DISK
        value: cloudinary
      - key: CLOUDINARY_URL
        value: cloudinary://582813253846428:ypCSd7IA_BrE_CR4ZgwUAcGWHog@dhdnbxy8j
      - key: CLOUDINARY_CLOUD_NAME
        value: dhdnbxy8j
      - key: CLOUDINARY_API_KEY
        value: "582813253846428"
      - key: CLOUDINARY_API_SECRET
        value: ypCSd7IA_BrE_CR4ZgwUAcGWHog
      - key: CLOUDINARY_PREFIX
        value: vibechat
